import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { AuthProvider } from "../context/AuthContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Local FusionX font (TTF) — place your TTF files in `assets/fonts`
// Expected filenames: assets/fonts/FusionX-Regular.ttf and FusionX-Bold.ttf
const fusionx = localFont({
  src: [
    {
      path: "../assets/fonts/mokoto-mokoto-regular-400.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-fusionx",
});

const pattanakarn = localFont({
  src: [
    {
      path: "../assets/fonts/fonnts.com-Pattanakarn_Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-pattanakarn",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${fusionx.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fusionx.variable} ${pattanakarn.className} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
